### PR TITLE
Added a little text on successes and impacts.

### PR DESCRIPTION
**Pull request by alancalder**

### CODE REVIEW

**Comment by alancalder** [comment]
Not sure what this comment will do....

**Comment by zingale** [comment]
you closed this accidentally?

**Comment by alancalder** [comment]
Ok, should have left it open! All looks good now.

ac

On Sun, Oct 11, 2015 at 11:53 AM, Michael Zingale notifications@github.com
wrote:

> Reopened #1 https://github.com/zingale/RFI_exascale/pull/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zingale/RFI_exascale/pull/1#event-432396243.

## 

Alan C. Calder
Department of Physics and Astronomy
State University of New York at Stony Brook
Stony Brook, NY 11794-3800

office: ESS 438
phone:  (631) 632-1176
fax:  (631) 632-1745
web: http://www.astro.sunysb.edu/acalder

**Comment by alancalder** [comment]
Will take a another pass in a bit.

On Sun, Oct 11, 2015 at 6:13 PM, Michael Zingale notifications@github.com
wrote:

> Merged #1 https://github.com/zingale/RFI_exascale/pull/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zingale/RFI_exascale/pull/1#event-432483569.

## 

Alan C. Calder
Department of Physics and Astronomy
State University of New York at Stony Brook
Stony Brook, NY 11794-3800

office: ESS 438
phone:  (631) 632-1176
fax:  (631) 632-1745
web: http://www.astro.sunysb.edu/acalder

**Comment by alancalder** [comment]
A little more work this evening. Pushed it into my forked version, but this pull request should see it?

**Pull request merged**
